@startuml

class GenerationView
class ClassDiagramGenerator
class Diagram
class PlantUmlClass
class PlantUmlClassDao

GenerationView --> ClassDiagramGenerator
ClassDiagramGenerator --> PlantUmlClassDao
ClassDiagramGenerator ..> PlantUmlClass

PlantUmlClassDao ..> PlantUmlClass
GenerationView ..> PlantUmlClass

@enduml
