@startuml
!include definitions.puml

controller ClassDiagramGenerator
controller FileUtilsFacade
controller PumlClassInterpreter [[file:///PumlClassInterpreter.puml]]

dao PumlClassDao

ClassDiagramGenerator --> FileUtilsFacade
    note on link
        readFilesFromDirectory(Path directory) : List<File>
        convertFilesToString(List<File> files) : String
    end note
ClassDiagramGenerator --> PumlClassInterpreter
    note on link
        interpret(String context) : List<PumlClass>
    end note
ClassDiagramGenerator --> PumlClassDao
    note on link
        void save(List<PumlClass>)
    end note
@enduml
