@startuml
actor user

!include definitions.puml

view GenerationView
controller ClassDiagramGenerator
model PlantUmlClassDao
model PlantUmlClass
model Diagram

user -right-> GenerationView
    note on link
        generateFromDirectory(path)
    end note
GenerationView --> ClassDiagramGenerator
    note on link
        generateFromDirectory(path)
    end note
ClassDiagramGenerator -right-> PlantUmlClassDao
    note on link
        save(plantUmlClass[])
    end note
PlantUmlClassDao .down.> PlantUmlClass
ClassDiagramGenerator ..> PlantUmlClass

@enduml
